//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-05-12 16:58:39 AuthBy:chenmm
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace DataEntity
{	
	[Table("Demo")] 
	public partial class DemoEntity
    {
		#region 属性
				
		/// <summary>
		/// 主键
		/// </summary>	
		[Key] 
		public int Pkid { get; set; }
				
		/// <summary>
		/// 广告名称
		/// </summary>	
		 
		public string AdvName { get; set; }
				
		/// <summary>
		/// 图片
		/// </summary>	
		 
		public string AdvImg { get; set; }
				
		/// <summary>
		/// 有效性
		/// </summary>	
		 
		public int Flag { get; set; }
				
		/// <summary>
		/// 排序号
		/// </summary>	
		 
		public int OrderNo { get; set; }
				
		/// <summary>
		/// 身份标识
		/// </summary>	
		 
		public string TokenId { get; set; }
				
		/// <summary>
		/// 创建日期
		/// </summary>	
		 
		public DateTime CreateDate { get; set; }
		 
      #endregion

	 	
		#region 设置默认值
		///<summary>
		///set default value
		///</summary>
		public void SetDefaultValue()
		{
			
			if (this.AdvName == null) this.AdvName = "";

			if (this.AdvImg == null) this.AdvImg = "";

			if (this.TokenId == null) this.TokenId = "";

			if (this.CreateDate.Year<1900) this.CreateDate =  new DateTime(1900,01,01);

		}
		#endregion

		#region 字段
		public static class Fields
		{ 
			public const string DBName= "cmm";

			public const string TbName = "dbo.Demo";

	   		public const string Pkid = "Pkid";
	   
	   		public const string AdvName = "AdvName";
	   
	   		public const string AdvImg = "AdvImg";
	   
	   		public const string Flag = "Flag";
	   
	   		public const string OrderNo = "OrderNo";
	   
	   		public const string TokenId = "TokenId";
	   
	   		public const string CreateDate = "CreateDate";
	   
	   	  }
		#endregion

		#region	基本SQL
        public static class Sql 
        {
		   
		    //所有字段组成的字符串,逗号分隔
		    public static string PartSqlFields=" Pkid,AdvName,AdvImg,Flag,OrderNo,TokenId,CreateDate"; 

			//From后面部分的Sql语句
		    public static string PartAfterFromSql=" cmm.dbo.Demo  WITH(NOLOCK) WHERE 1=1 "; 
			
			//查询sql
			public static string SqlDetail="SELECT Pkid,AdvName,AdvImg,Flag,OrderNo,TokenId,CreateDate FROM cmm.dbo.Demo  WITH(NOLOCK) WHERE 1=1  ";
        }
		#endregion
    }
}

